### ISSUE TITLE
WooCommerce "My Account" widget urls incorrect

### ISSUE THREAD

**Issue by GydeBC** [timstrifler/exclusive-addons-for-elementor#22]
Hi, your "My account" widgets urls are incorrect, the URLs in the navigation all refer to <a href="https://example.com/woocommerce-endpoint/">Wocommercse Endpoint</a> , which however should be <a href="https://example.com/**my-account**/woocommerce-endpoint/">Wocommercse Endpoint</a>. Br, Gyde

**Comment by GydeBC** [comment]
The /my-account/ part is missing in the url

**Comment by GydeBC** [comment]
Hi,
When using your woo-my-account widget, the links that are used are missing the url term my-account. So I had to make redirections to all e.g. Edit adress. Because your widget's link was patentsmarter.com/edit-address, but should be patentsmarter.com/my-account/edit-address

Does it make sense now?

Br, Gyde

**Comment by devjennz** [comment]
This issue is related to WooCommerce. Please refer to the following link to configure Endpoints:
[https://woocommerce.com/document/woocommerce-endpoints](https://woocommerce.com/document/woocommerce-endpoints)

Also please check the following link from WooCommerce support:
[https://wordpress.org/support/topic/woocommerce-endpoints-404-error/](https://wordpress.org/support/topic/woocommerce-endpoints-404-error/)
